worker_processes auto;
events {
    worker_connections 10000; # Suportar a cacetada de conexões do teste de carga
}
http {
    access_log off; # Desativar logs de escrita em disco (gasta muita CPU!)
    sendfile on;
    
    upstream api_servers {
        server 127.0.0.1:8001;
        server 127.0.0.1:8002;
        keepalive 200; # Crucial: Mantém conexões TCP vivas com o Python
    }

    server {
        listen 9999; # Porta principal da Rinha
        
        location / {
            proxy_pass http://api_servers;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
        }
    }
}
