events{}

http {
	upstream backend {
	#least_conn:
		server 0.0.0.0:8101; 
		server 0.0.0.0:8103; 
		server 0.0.0.0:8104; 
	}

	server {
		listen 8200;

		location / {
			proxy_pass http://backend;
		}
	}
}
